/*
 * THIS FILE WAS GENERATED BY D:\WATTCP\UTIL\WC_ERR.EXE. DO NOT EDIT.
 *
 * Watt-32 sys_errlist replaces vendor's sys_errlist
 */

#ifndef __WATCOMC__
#error This file is only for use by "__WATCOMC__"
#endif

char __syserr42[] = "Operation would block (EWOULDBLOCK)";
char __syserr13[] = "Argument too large (EDOM)";
char __syserr14[] = "Result too large (ERANGE)";
char __syserr02[] = "Arg list too big (E2BIG)";
char __syserr06[] = "Permission denied (EACCES)";
char __syserr18[] = "Resource unavailable, try again (EAGAIN)";
char __syserr04[] = "Bad file number (EBADF)";
char __syserr19[] = "Device or resource busy (EBUSY)";
char __syserr17[] = "Child does not exist (ECHILD)";
char __syserr15[] = "Resource deadlock would occur (EDEADLK)";
char __syserr07[] = "File exists (EEXIST)";
char __syserr34[] = "Bad address (EFAULT)";
char __syserr20[] = "File too large (EFBIG)";
char __syserr16[] = "System call interrupted (EINTR)";
char __syserr09[] = "Invalid argument (EINVAL)";
char __syserr21[] = "I/O error (EIO)";
char __syserr22[] = "Is a directory (EISDIR)";
char __syserr11[] = "Too many open files (EMFILE)";
char __syserr24[] = "Too many links (EMLINK)";
char __syserr35[] = "Filename too long (ENAMETOOLONG)";
char __syserr10[] = "File table overflow (ENFILE)";
char __syserr36[] = "No such device (ENODEV)";
char __syserr01[] = "No such file or directory (ENOENT)";
char __syserr03[] = "Exec format error (ENOEXEC)";
char __syserr37[] = "No locks available in system (ENOLCK)";
char __syserr05[] = "Not enough memory (ENOMEM)";
char __syserr12[] = "No space left on device (ENOSPC)";
char __syserr38[] = "Unknown system call (ENOSYS)";
char __syserr23[] = "Not a directory (ENOTDIR)";
char __syserr39[] = "Directory not empty (ENOTEMPTY)";
char __syserr26[] = "Not a character device (ENOTTY)";
char __syserr27[] = "No such device or address (ENXIO)";
char __syserr28[] = "Not owner (EPERM)";
char __syserr29[] = "Broken pipe (EPIPE)";
char __syserr30[] = "Read-only file system (EROFS)";
char __syserr31[] = "Illegal seek (ESPIPE)";
char __syserr32[] = "No such process (ESRCH)";
char __syserr08[] = "Cross-device link (EXDEV)";
char __syserr43[] = "No more files (ENMFILE)";
char __syserr44[] = "Operation now in progress (EINPROGRESS)";
char __syserr45[] = "Operation already in progress (EALREADY)";
char __syserr46[] = "Socket operation on non-socket (ENOTSOCK)";
char __syserr47[] = "Destination address required (EDESTADDRREQ)";
char __syserr48[] = "Message too long (EMSGSIZE)";
char __syserr49[] = "Protocol wrong type for socket (EPROTOTYPE)";
char __syserr50[] = "Protocol option not available (ENOPROTOOPT)";
char __syserr51[] = "Protocol not supported (EPROTONOSUPPORT)";
char __syserr52[] = "Socket type not supported (ESOCKTNOSUPPORT)";
char __syserr53[] = "Operation not supported on socket (EOPNOTSUPP)";
char __syserr54[] = "Protocol family not supported (EPFNOSUPPORT)";
char __syserr55[] = "Address family not supported by protocol (EAFNOSUPPORT)";
char __syserr56[] = "Address already in use (EADDRINUSE)";
char __syserr57[] = "Can't assign requested address (EADDRNOTAVAIL)";
char __syserr58[] = "Network is down (ENETDOWN)";
char __syserr59[] = "Network is unreachable (ENETUNREACH)";
char __syserr60[] = "Network dropped connection on reset (ENETRESET)";
char __syserr61[] = "Software caused connection abort (ECONNABORTED)";
char __syserr62[] = "Connection reset by peer (ECONNRESET)";
char __syserr63[] = "No buffer space available (ENOBUFS)";
char __syserr64[] = "Socket is already connected (EISCONN)";
char __syserr65[] = "Socket is not connected (ENOTCONN)";
char __syserr66[] = "Can't send after socket shutdown (ESHUTDOWN)";
char __syserr67[] = "Connection timed out (ETIMEDOUT)";
char __syserr68[] = "Connection refused (ECONNREFUSED)";
char __syserr69[] = "Host is down (EHOSTDOWN)";
char __syserr70[] = "No route to host (EHOSTUNREACH)";
char __syserr71[] = "Stale NFS file handle (ESTALE)";
char __syserr72[] = "Too many levels of remote in path (EREMOTE)";
char __syserr73[] = "RPC struct is bad (EBADRPC)";
char __syserr74[] = "RPC version wrong (ERPCMISMATCH)";
char __syserr75[] = "RPC prog. not avail (EPROGUNAVAIL)";
char __syserr76[] = "RPC Program version wrong (EPROGMISMATCH)";
char __syserr77[] = "Bad procedure for program (EPROCUNAVAIL)";
char __syserr40[] = "Illegal multibyte sequence (EILSEQ)";
char __syserr78[] = "Invalid function number (EINVFNC)";
char __syserr79[] = "Path not found (ENOPATH)";
char __syserr80[] = "Memory area destroyed (ECONTR)";
char __syserr81[] = "Invalid memory block address (EINVMEM)";
char __syserr82[] = "Invalid environment (EINVENV)";
char __syserr83[] = "Invalid format (EINVFMT)";
char __syserr84[] = "Invalid access code (EINVACC)";
char __syserr85[] = "Invalid data (EINVDAT)";
char __syserr86[] = "Attempt to remove current directory (ECURDIR)";
char __syserr87[] = "Not same device (ENOTSAM)";
char __syserr33[] = "Text file busy (ETXTBSY)";
char __syserr25[] = "Block device required (ENOTBLK)";
char __syserr88[] = "Structure needs cleaning (EUCLEAN)";
char __syserr89[] = "Too many references (ETOOMANYREFS)";
char __syserr90[] = "Too many levels of symbolic links (ELOOP)";
char __syserr91[] = "Too many processes (EPROCLIM)";
char __syserr92[] = "Too many users (EUSERS)";
char __syserr93[] = "Disc quota exceeded (EDQUOT)";
char __syserr94[] = "RVD related disk error (EVDBAD)";
char __syserr95[] = "Out of remote working directory stuctures (ENORMTWD)";
char __syserr96[] = "Value too large (EOVERFLOW)";

char *SYS_ERRLIST[] = {
    __syserr00,  __syserr01,  __syserr02,  __syserr03,  __syserr04, 
    __syserr05,  __syserr06,  __syserr07,  __syserr08,  __syserr09, 
    __syserr10,  __syserr11,  __syserr12,  __syserr13,  __syserr14, 
    __syserr15,  __syserr16,  __syserr17,  __syserr18,  __syserr19, 
    __syserr20,  __syserr21,  __syserr22,  __syserr23,  __syserr24, 
    __syserr25,  __syserr26,  __syserr27,  __syserr28,  __syserr29, 
    __syserr30,  __syserr31,  __syserr32,  __syserr33,  __syserr34, 
    __syserr35,  __syserr36,  __syserr37,  __syserr38,  __syserr39, 
    __syserr40,  __syserr00,  __syserr42,  __syserr43,  __syserr44, 
    __syserr45,  __syserr46,  __syserr47,  __syserr48,  __syserr49, 
    __syserr50,  __syserr51,  __syserr52,  __syserr53,  __syserr54, 
    __syserr55,  __syserr56,  __syserr57,  __syserr58,  __syserr59, 
    __syserr60,  __syserr61,  __syserr62,  __syserr63,  __syserr64, 
    __syserr65,  __syserr66,  __syserr67,  __syserr68,  __syserr69, 
    __syserr70,  __syserr71,  __syserr72,  __syserr73,  __syserr74, 
    __syserr75,  __syserr76,  __syserr77,  __syserr78,  __syserr79, 
    __syserr80,  __syserr81,  __syserr82,  __syserr83,  __syserr84, 
    __syserr85,  __syserr86,  __syserr87,  __syserr88,  __syserr89, 
    __syserr90,  __syserr91,  __syserr92,  __syserr93,  __syserr94, 
    __syserr95,  __syserr96, 
};

